name: flutter_application_1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  email_validator: ^2.1.17
  motion_toast: ^2.8.0
  flutter_datetime_picker: ^1.5.1
  table: ^0.0.1-dev
  cli_table: ^1.0.2
  data_table_2: ^2.5.11
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - asset/image/
  uses-material-design: true

